language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer install

script: vendor/bin/phpunit
